### ISSUE TITLE
panic: role unknown for operator ID 0

### ISSUE THREAD

**Issue by Segergren** [redraskal/r6-dissect#103]
Hi, I have recently got this issue. Looks like the same as #66.

```
panic: role unknown for operator ID 0

goroutine 1 [running]:
github.com/redraskal/r6-dissect/dissect.Operator.Role(...)
        /github/workspace/dissect/operator_roles.go:86
github.com/redraskal/r6-dissect/dissect.readSpawn(0xc0048fc008)
        /github/workspace/dissect/site.go:32 +0x505
github.com/redraskal/r6-dissect/dissect.(*Reader).Read(0xc0048fc008)
        /github/workspace/dissect/reader.go:221 +0x543
github.com/redraskal/r6-dissect/dissect.(*MatchReader).read(0xc0002e8460, 0x3)
        /github/workspace/dissect/match.go:73 +0x210
github.com/redraskal/r6-dissect/dissect.(*MatchReader).Read(...)
        /github/workspace/dissect/match.go:78
main.writeMatch(0x103e015?, {0x103bdac, 0x4}, {0x10ca780, 0xc00008c1f8})
        /github/workspace/main.go:155 +0x72
main.main()
        /github/workspace/main.go:64 +0x547
```
I'll attach the .rec files. Looks like the `Match-2024-08-13_23-36-17-242-R04.rec` is the one causing issues.
[Match-2024-08-13_23-36-17-242.zip](https://filebin.net/6ltho29i6mbalhlq/Match-2024-08-13_23-36-17-242.zip) (too large for Github)
[Match-2024-08-13_23-36-17-242.zip Mirror](https://file.io/fBSDqgS4VATH)

**Comment by redraskal** [comment]
likely fixed in this release: https://github.com/redraskal/r6-dissect/releases/tag/v0.21.2
